import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/reduxProvider";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ludo Game",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  manifest: "/manifest.json",
  themeColor: "#fff",
  appleWebApp: {
    title: "Ludo Game",
    statusBarStyle: "black-translucent",
  },
  icons: [
    {
      url: "/web/icon-192.png",
      sizes: "192x192",
      type: "image/png",
    },
    {
      url: "/web/icon-512.png",
      sizes: "512x512",
      type: "image/png",
    },
  ],
  openGraph: {
    title: "Ludo Game",
    description: "A Ludo Game built with Next.js.",
    images: [
      {
        url: "/images/logo.png",
        width: 600,
        height: 1200,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#fff" />
        <link rel="apple-touch-icon" sizes="192x192" href="/images/ludo.png" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
